variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    DEVEL_HPP_DIR: "/workspace"
    BUILD_TYPE: "Release"

.build_template: &build_definition
    stage: build
    script:
      - export INSTALL_DOCUMENTATION=OFF
      - $CI_PROJECT_DIR/scripts/auto-install-hpp.sh --branch ${CI_COMMIT_REF_NAME} --gitrepo ${CI_PROJECT_URL}/raw --target test-ci
    after_script:
      - mv $DEVEL_HPP_DIR $CI_PROJECT_DIR
    artifacts:
      expire_in: 1 day
      when: always
      paths:
        - workspace

.test_template: &test_definition
    stage: test
    script:
      - rm -rf /workspace
      - mv workspace /
      - status=0
      - echo -e "#!/bin/bash\nsource $DEVEL_HPP_DIR/config.sh\ncd $DEVEL_HPP_DIR/src/\$1/build-rel && make CTEST_OUTPUT_ON_FAILURE=1 test" > $DEVEL_HPP_DIR/test.sh || status=1
      - cat $DEVEL_HPP_DIR/test.sh
      - set +e
      - chmod u+x $DEVEL_HPP_DIR/test.sh
      - $DEVEL_HPP_DIR/test.sh hpp-util                    || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-fcl                     || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-pinocchio               || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-statistics              || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-constraints             || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-core                    || status=1
        #- $DEVEL_HPP_DIR/test.sh hpp-corbaserver          || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-manipulation            || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-manipulation-urdf       || status=1
        #- $DEVEL_HPP_DIR/test.sh hpp-manipulation-corba   || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-walkgen                 || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-wholebody-step          || status=1
        #- $DEVEL_HPP_DIR/test.sh hpp-wholebody-step-corba || status=1
      - $DEVEL_HPP_DIR/test.sh hpp-rbprm                   || status=1
      - set -e
      - exit $status
    allow_failure: true
    after_script:
      - mv $DEVEL_HPP_DIR $CI_PROJECT_DIR
    artifacts:
      expire_in: 1 day
      when: always
      paths:
        - workspace

.doc_template: &doc_definition
    stage: deploy
    script:
      - rm -rf /workspace
      - mv workspace /
      - echo -e "#!/bin/bash\nsource $DEVEL_HPP_DIR/config.sh\nmake -C $DEVEL_HPP_DIR/src -s all" > $DEVEL_HPP_DIR/doc.sh
      - cat $DEVEL_HPP_DIR/doc.sh
      - chmod u+x $DEVEL_HPP_DIR/doc.sh
      - export INSTALL_DOCUMENTATION=ON
        #- make -C $DEVEL_HPP_DIR/src -s all
      - $DEVEL_HPP_DIR/doc.sh
      - tar czf ${DEVEL_HPP_DIR}/hpp.${CI_COMMIT_REF_NAME}.`date +"%Y%m%d"`.tar.gz $DEVEL_HPP_DIR/install/share/doc
    after_script:
      - mv $DEVEL_HPP_DIR $CI_PROJECT_DIR
    allow_failure: true
    artifacts:
      expire_in: 1 day
      when: always
      paths:
        - workspace

master-build:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/master-premade:16.04
    only:
      - future
    <<: *build_definition

ubuntu-14.04-build:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/ubuntu-14.04-premade:14.04
    only:
      - ubuntu-14.04
    <<: *build_definition

devel-build:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/devel-premade:16.04
    only:
      -  devel
    <<: *build_definition

master-test:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/master-premade:16.04
    dependencies:
      - master-build
    only:
      - future
    <<: *test_definition

ubuntu-14.04-test:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/ubuntu-14.04-premade:14.04
    dependencies:
      - ubuntu-14.04-build
    only:
      - ubuntu-14.04
    <<: *test_definition

devel-test:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/devel-premade:16.04
    dependencies:
      - devel-build
    only:
      -  devel
    <<: *test_definition

master-doc:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/master-premade:16.04
    dependencies:
      - master-build
    only:
      - future
    <<: *doc_definition

ubuntu-14.04-doc:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/ubuntu-14.04-premade:14.04
    dependencies:
      - ubuntu-14.04-build
    only:
      - ubuntu-14.04
    <<: *doc_definition

devel-doc:
    image: eur0c.laas.fr:5000/humanoid-path-planner/hpp-doc/devel-premade:16.04
    dependencies:
      - devel-build
    only:
      -  devel
    <<: *doc_definition
